// <auto-generated />
using System;
using EFCoreModelApp.DbConfiguration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreModelApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630022758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("EFCoreModelApp.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            Name = "HR"
                        },
                        new
                        {
                            DepartmentID = 2,
                            Name = "Engineering"
                        },
                        new
                        {
                            DepartmentID = 3,
                            Name = "Finance"
                        },
                        new
                        {
                            DepartmentID = 4,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("EFCoreModelApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            DepartmentID = 1,
                            FirstName = "Rafael",
                            HireDate = new DateTime(2026, 6, 29, 23, 27, 57, 807, DateTimeKind.Local).AddTicks(7181),
                            LastName = "Carvalho"
                        },
                        new
                        {
                            EmployeeID = 2,
                            DepartmentID = 1,
                            FirstName = "Larissa",
                            HireDate = new DateTime(2026, 6, 29, 23, 27, 57, 809, DateTimeKind.Local).AddTicks(9604),
                            LastName = "Gomes"
                        },
                        new
                        {
                            EmployeeID = 3,
                            DepartmentID = 2,
                            FirstName = "Maria",
                            HireDate = new DateTime(2026, 6, 29, 23, 27, 57, 809, DateTimeKind.Local).AddTicks(9623),
                            LastName = "Oliveira"
                        },
                        new
                        {
                            EmployeeID = 4,
                            DepartmentID = 2,
                            FirstName = "Pedro",
                            HireDate = new DateTime(2026, 6, 29, 23, 27, 57, 809, DateTimeKind.Local).AddTicks(9626),
                            LastName = "Santos"
                        },
                        new
                        {
                            EmployeeID = 5,
                            DepartmentID = 2,
                            FirstName = "Mariana",
                            HireDate = new DateTime(2026, 6, 29, 23, 27, 57, 809, DateTimeKind.Local).AddTicks(9628),
                            LastName = "Costa"
                        },
                        new
                        {
                            EmployeeID = 6,
                            DepartmentID = 3,
                            FirstName = "João",
                            HireDate = new DateTime(2026, 6, 29, 23, 27, 57, 809, DateTimeKind.Local).AddTicks(9629),
                            LastName = "Silva"
                        },
                        new
                        {
                            EmployeeID = 7,
                            DepartmentID = 4,
                            FirstName = "Beatriz",
                            HireDate = new DateTime(2026, 6, 29, 23, 27, 57, 809, DateTimeKind.Local).AddTicks(9630),
                            LastName = "Almeida"
                        },
                        new
                        {
                            EmployeeID = 8,
                            DepartmentID = 4,
                            FirstName = "Gabriel",
                            HireDate = new DateTime(2026, 6, 29, 23, 27, 57, 809, DateTimeKind.Local).AddTicks(9631),
                            LastName = "Rodrigues"
                        });
                });

            modelBuilder.Entity("EFCoreModelApp.Models.Employee", b =>
                {
                    b.HasOne("EFCoreModelApp.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCoreModelApp.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
