@LoggingSample_HostAddress = http://localhost:5259

# Correct Usage Execution Test
GET {{LoggingSample_HostAddress}}/api/ErrorHandling/division?numerator=77&denominator=3
Accept: application/json

###

# Handled Exception Test
GET {{LoggingSample_HostAddress}}/api/ErrorHandling/division?numerator=10&denominator=0
Accept: application/json

###

# Unhandled Global Exception Test
GET {{LoggingSample_HostAddress}}/api/ErrorHandling/throw-global
Accept: application/json

###